svsticky/sadserver

ansible/templates/var/www/koala/.rbenv-vars.j2

Add Sentry DSN  to env vars

---

README.md
docs/updating-ssh-keys.md

Added step-by-step instructions for setting up a new development or production server.
Inspired by issue #159

Documentation enhancements based on #159

---

README.md

This fixes #187.
Added some things that are said in other parts of the readme to the setup-guide.

Adds some clarification to the README

---

ansible/scripts/run-playbook.sh

Read sudo password from Vault

---

ansible/playbooks/koala/activestorage-migration.yml
ansible/tasks/koala.yml

https://github.com/svsticky/constipated-koala/pull/346  
https://github.com/svsticky/sadserver/issues/205

Add one-off playbook for ActiveStorage migration

---

ansible/tasks/nginx.yml
ansible/templates/etc/nginx/sites-available/dgdarc.conf.j2

Database and old webroot still need to backed up and cleaned up.

Add plain nginx config to redirect DGDARC

---

ansible/templates/etc/nginx/sites-available/wintersport.conf.j2

On request of the wintersport committee

changed url to slides

---

ansible/tasks/oauth2-proxy.yml

Switched to new version of oauth2-proxy in different repo

---

ansible/main.yml
ansible/tasks/public_files.yml
ansible/templates/etc/nginx/sites-available/public.conf.j2
ansible/templates/var/www/public/theme/footer.html
ansible/templates/var/www/public/theme/header.html.j2
ansible/templates/var/www/public/theme/style.css

Added files for public.svsticky.nl

---

ansible/main.yml
ansible/tasks/nix.yml

Add task to install Nix

---

.github/workflows/lint.yml
ansible/templates/etc/nginx/sites-available/koala.j2

Adds caching for active storage for koala

Active storage caching

---

ansible/main.yml
ansible/roles/databases/tasks/main.yml

And remove the 'remove mariadb' stuff

Move databases task to role

---

ansible/roles/files_website/files/style.css
ansible/roles/public_files/files/style.css

latest version of style with de-cluttered mobile view

Update files websites style

---

ansible/main.yml
ansible/roles/doorgeefluik/files/.env
ansible/roles/doorgeefluik/handlers/main.yml
ansible/roles/doorgeefluik/tasks/main.yml
ansible/roles/doorgeefluik/templates/.env.j2
ansible/roles/doorgeefluik/templates/doorgeefluik.conf.j2
ansible/roles/doorgeefluik/templates/doorgeefluik.service.j2
ansible/roles/static-sticky/templates/svsticky.conf.j2

doorgeefluik

---

.github/workflows/lint.yml
ansible/nix/ansible-mitogen.nix

Update Nix in CI

---

ansible/roles/koala/tasks/main.yml
ansible/roles/koala/templates/systemd/koala-payment-mail.service.j2
ansible/roles/koala/templates/systemd/koala-payment-mail.timer.j2

This adds the timer and service for the new Koala payment mails.
Also see this PR svsticky/constipated-koala/pull/981

Koala payment mail timer

---

ansible/roles/koala/handlers/main.yml
ansible/roles/koala/tasks/main.yml

restart sidekiq on koala clone and .env change

---

.github/workflows/lint.yml

newer is better (hopefully)
Edit: it was better :)

ci(bump install_nix github action version)

---

ansible/group_vars/all/users.yml

I will run the users role on staging to ensure his keys are in the authorized keys file.
heads up: @SilasPeters, you don't have to do anything but wanted to keep you in the loop

Adds tobias as an admin user

---

ansible/group_vars/all/users.yml

Allow SSH Keys of SilasPeters

---

.github/workflows/projects.yml

Perhaps the title says it all. This is a really simple workflow, and it's open for any changes or adjustments.

New workflow for adding opened issues to the CommITCrowd project

---

ansible/group_vars/all/users.yml

Updated pxl rights

---

ansible/roles/backups/templates/backup-to-s3.sh.j2
ansible/roles/node/tasks/main.yml

- updating node v14 -> v20
- skipping the install prompt of npx
- creating a new management token

fix contentful backups by:

---

ansible/roles/databases/tasks/main.yml
ansible/roles/doorgeefluik/tasks/main.yml

I tested the main koala user, but not the manual user.

chore: replaced deprecated privilege code

---

ansible/group_vars/all/vars.yml
ansible/group_vars/all/websites.yml
ansible/group_vars/production/vars.yml
ansible/group_vars/staging/vars.yml
ansible/main.yml
ansible/roles/aas/templates/config.json.j2
ansible/roles/aas/templates/sudoers.j2
ansible/roles/intro_website/readme.md
ansible/roles/intro_website/tasks/main.yml
ansible/roles/intro_website/templates/deploy-intro-website.service.j2
ansible/roles/intro_website/templates/deploy-intro-website.sh.j2
ansible/roles/intro_website/templates/intro-website.conf.j2

Has been tested on staging, but can only be fully tested on production :)

feat: intro website!

---

ansible/roles/websites/templates/intro-cs.conf.j2

as title says. Remove old nginx config, explain why we use 308, and return 308

give intro-cs.nl a 308 to intro.svsticky.nl

---

ansible/group_vars/all/websites.yml
ansible/main.yml
ansible/roles/rottenspringbok/tasks/main.yml
ansible/roles/rottenspringbok/templates/.env.j2
ansible/roles/rottenspringbok/templates/rottenspringbok.conf.j2
ansible/roles/rottenspringbok/vars/main.yml

The random name selector of Sticky

feat: rottenspringbok sadserver settings
