ansible/scripts/fetch-keys-for-gh-user.sh, ansible/scripts/run-playbook.sh, ansible/templates/usr/local/bin/backup-to-s3.sh.j2
This fixes a bug in Bash's [parameter substitution] we use in our shell scripts. The old construction would set a variable to the default "x" when the var *was* already set, instead of when it *wasn't* set. Since most of our tests don't use the value, this hasn't had consequences in use. The ":" makes sure the var is also substituted when the var is assigned a null value.
Actually became aware of this because I used the construction in a personal script as well, and it errored because of some race condition 😅 
[parameter substitution]:
https://www.tldp.org/LDP/abs/html/parameter-substitution.html
=> Fix variable bug in Bash scripts

ansible/playbooks/restore-backup.yml, ansible/scripts/run-playbook.sh, ansible/templates/home/ansible/.aws/config.j2, ansible/templates/usr/local/bin/backup-to-s3.sh.j2, docs/deployment-new-production.md
This does two things.
- The backup size is added to backup notifications in Slack. This makes it possible to glance at that channel to see if a backup hasn't become ~0MB all of a sudden. It also changes the backup time in the notification to be in our local timezone.
- A separate playbook is added. It takes the backups made in production, and tries to restore them. We can use this periodically on a staging server to see if the backups still actually work, or use it to migrate the production environment. It checks the hashes, unpacks it to the paths as specified in the backups itself, and imports the databases. The only thing you have to do yourself, when deploying on staging, is change the restored paths of webroots to match the hostnames used in staging (*.**dev**.svsticky.nl).
Fixes …
=> Verify integrity of backups

README.md, ansible/bootstrap-new-host.yml, ansible/hosts
Ansible has stable Python 3.5+ support since Ansible 2.5, so we don't need Python 2.7 any more.
**Should not be merged before #175 is and we're creating a new prod environment.**
=> Let Ansible use Python3 on remote

ansible/templates/usr/local/bin/backup-to-s3.sh.j2
This changes the backup script to create the backup archives in memory, instead of in a tempfile. So we don't need twice the disk space, and our monitoring won't be afraid that we will run out of disk space.
Fixes #176.
=> Use memory instead of temp file during backups

README.md, ansible/scripts/get-vault-pass-from-bitwarden-client.sh, ansible/scripts/run-playbook.sh
If available, get the Vault passphrase from the unlocked Bitwarden Vault in the environment, performed using its CLI. If you don't have the Bitwarden CLI installed, it'll prompt as usual.
=> Use Bitwarden CLI to supply Vault passphrase

ansible/tasks/pretix.yml
It is now possible to use Mollie as a payments provider for Pretix, I think that Execut will want this since it's cheaper. Also adds some new features by adding plugins.
=> WIP: Update pretix version, add plugins

ansible/templates/etc/fail2ban/filter.d/koala404.conf.j2, ansible/templates/etc/fail2ban/jail.local.j2
This PR adds a fail2ban filter and jail for 404's on Koala's activities, as discussed in Slack.
Testable by spamming this in terminal, which should ban you after the fifth 404 within 60 seconds:
```
curl -b 'constipated_koala_session=anlYajZJWFBkcUxRSk8rRkVJWUtlNEVTNFJDZ2ZZMXpGdTRpbFFITS9PbzRnVGVVZm0wbVN5bkcyQ0hDY241dlVhNStyUWRwQ2Vnak5nWllKNHp3Qjd6L09PMFk0R0FRRmNXaU4vV3pkMnpEYXZ0aGUwNzRUYm9WMnpuNjhPcnNxd3JrUzErTnd4WjVPcWNaS2JlMkI5VjhzMXlMV0pvOVJjbFp0NUdIY0ZSOHdHTjdrMmRIVlQxRkFNeDlMbHAxbm9Jb2lpbzNtREdPVkJHaThQYzgxMUVZOGlJeXA0S2dDakNzRDQxMmF4ZG13RVlMcitndHdmbnUwQzd6TC91N0tocG5TbWFHWlBVVVY2V2I0YlB5Rjh5cWxjdjRidnN5eUxrelZHdFV0S3FDeU4yY2svUi9kV0I5elpIWnBqNytLTXBZYnNHRUR1L2doQnVCY1duQjB3PT0tLWQ3a295NlJMZ2dVcWdYdWk5cFpaN3c9PQ%3D%3D--954753f9429be45bab05dd42552ad42878fd4c14' --insecure …
```
=> Add fail2ban jail for 404's on activities, findtime option

ansible/scripts/csvpseudo.py, ansible/templates/etc/nginx/includes/execut-referer-tracking.conf.j2, ansible/templates/etc/nginx/nginx.conf.j2, ansible/templates/etc/nginx/sites-available/website.conf.j2
Adds logging of Referer headers for visits to the Execut website. Logging is only done if:
1. The Do Not Track header is not enabled (so absent or 0), and
2. The Referer header specifies a referrer not under *.execut.nl (we only care about incoming visits).
All Execut websites log referrers to `/var/log/nginx/execut_referer_tracking` in a Tab-seperated file containing Referer, URL, timestamp and IP. This file needs to be either pseudonymized or anonymized before sharing the data.
Also adds a new website variable `extra_includes` that can be reused to enable includes without creating yet another copy of the website config template.
And yes, Referer is a misspelling, but it is the correct header name: https://en.wikipedia.org/wiki/HTTP_referer
To do:
=> Add Referer tracking for Execut websites

ansible/tasks/packages.yml, ansible/tasks/static-sticky.yml, ansible/templates/etc/nginx/sites-available/svsticky.conf.j2, ansible/templates/etc/systemd/system/deploy-static-sticky.service.j2, ansible/templates/usr/local/bin/deploy-static-sticky.sh.j2
This adds a few calls to GitHub's [Deployments API](https://developer.github.com/v3/repos/deployments/), to allow insight into deployments of the website. Most importantly, this generates webhook events that can be consumed by GitHub's Slack app, so it posts messages in a Slack channel of the CommIT's choosing.
This also creates a deployments overview on GitHub, as in the example [here](https://github.com/zeit/docs/deployments). Different from there, I used the "deployed" link ( `log_url`) to link to the log output of the build. This allows the CommIT to see what went wrong, in case a deploy has failed.
This means the build log is public, but I think that's ok? If not, we could add Basic Auth to the logs directory.
If the CommIT finds this useful, I'll finish it up by adding the access …
=> Add status messages for static-sticky deployments 

ansible/handlers/main.yml, ansible/main.yml, ansible/tasks/crazy88bot.yml, ansible/tasks/users.yml, ansible/templates/etc/systemd/system/crazy88bot.service.j2, ansible/templates/usr/local/bin/backup-to-s3.sh.j2
@Phavion (Niels Kwadijk) made a bot that is to be used during the introduction for running the Crazy 88 challenge and accepting submissions from teams via Telegram.
This PR adds a section to the playbook that adds a user for the bot, clones the code, creates a venv, and starts and enables a systemd service for it when running in production.
=> Add setup for Telegram bot for Crazy 88

ansible/playbooks/koala/.maintenance-off.yml, ansible/playbooks/koala/.maintenance-on.yml, ansible/tasks/koala.yml, ansible/templates/etc/systemd/system/sidekiq.service.j2
This PR:
- Alters the template for `sidekiq.service` to include the queues to process jobs
for, which should fix the problem we have where mails aren't being sent,
- Alters `koala.yml` to remove `sidekiq.service` from the list of timers to only run
in production, and
- Alters Koala's maintenance mode playbooks to also stop and start `sidekiq.service`
as appropriate, to ensure that no background jobs can be run while maintenance mode
is active.
=> Koala sidekiq changes

README.md, ansible/scripts/get-vault-pass-from-bitwarden-client.sh, ansible/scripts/mariadb-root-tunnel.sh, ansible/scripts/run-playbook.sh, ansible/scripts/slacktee.sh, ansible/shell.nix
This PR alters the scripts we use to run the playbook (mainly `run-playbook.sh`) to automatically run in the Nix-managed environment via `nix-shell` as a shebang.
=> Automatically run `run-playbook.sh` in the Nix environment

ansible/default.nix, ansible/nix/sources.json
This PR alters the Nix config to
- Add a new source `nixpkgs-new` to `niv` that pins the latest unstable Nixpkgs,
- Alter the Nix environment to get `bw` from this Nixpkgs snapshot, to use the newest version (1.19.1) instead of the currently-pinned version that can't log in anymore,
- Alter the Nix environment to move `ansible-lint` out of the Python environment to prevent future problems when upgrading Ansible.
With this PR I can `nix run -c bw login` again.
=> Upgrade `bw` version

ansible/main.yml, ansible/roles/outline/tasks/main.yml, ansible/roles/outline/templates/outline.env.j2, ansible/roles/outline/templates/outline.service.j2
Updates Outline to 0.59.0 and a new oauth method supplied by outline. Decreases the amount of threads so it doesn't consume the entire server
=> Outline production ready

ansible/roles/koala/templates/systemd/koala.service.j2, ansible/roles/pretix/templates/systemd/pretix-runperiodic.service.j2
I came across this when writing a PR to cleanup mysql (see #232).
This should be an easy deploy, but I'm waiting for a work session to perform it as it takes a little downtime.
=> Require postgres in servicefile instead of mysql

ansible/roles/oauth2_proxy/templates/oauth2-proxy-admin.service.j2, ansible/roles/oauth2_proxy/templates/oauth2-proxy.service.j2
In #370 I kinda updated the proxy, but didn't realize the executable name changed from `oauth2_proxy` to `oauth2-proxy`.
This PR fixes the oversight and closes #352
=> update oauth2proxy systemd templates

README.md
Today we were teaching some new committee members on how to deploy a new droplet. The current guide is quite outdated, this new one should be more accurate
=> Installation guide update

ansible/default.nix, ansible/deploy.py
=> add from until options to deploy.py

ansible/group_vars/all/websites.yml, ansible/roles/packages/tasks/main.yml
Execut website is now hosted on Github pages, so the DNS no longer points at us.
=> Remove all execut.nl subdomains

ansible/roles/nix/files/install, ansible/roles/nix/tasks/main.yml
This PR updates the install script from to the latest version. The script has quite simply been replaced.
It has been tested by deploying to a whole new server.
Reason is that it became too outdated to be able to install with current config.
=> bump: nix 2.24

ansible/group_vars/production/vars.yml, ansible/group_vars/staging/vars.yml, ansible/roles/pretix/tasks/main.yml, ansible/roles/pretix/templates/pretix_maintenance.conf.j2, ansible/roles/pretix/templates/pretix_maintenance.html.j2
- Add variable `pretix_maintenance_mode`, setting to true will yield:
- Pin `pip` version. It was broken.
=> Add support for pretix maintenance mode, using variable.

ansible/group_vars/production/vars.yml, ansible/group_vars/staging/vars.yml, ansible/roles/koala/templates/.env.j2, ansible/roles/mongoose/templates/.env.j2
made envVar for mongoose mollie secret, and add it. As per request of @TobiasDeBruijn
=> added mollie secrets for mongoose

ansible/group_vars/staging/vars.yml, ansible/roles/chroma/tasks/main.yaml, ansible/roles/digidecs/tasks/main.yml, ansible/roles/rooster/tasks/main.yaml
See svsticky/chroma/issues/44
If the git tag is 'latest' and not actually a git tag, the url pointing to the artifacts will be adjusted to not specify a tag but the latest downloads
=> fix: latest tag now works for artifacts based deploy

ansible/roles/koala/templates/nginx.conf.j2
Aims to solve the 422 errors when authenticating users signup up at alternative domains.
Previously we let nginx do the routing to several sign up pages.
Don't know if this was not the case in the past, but actually signing up was impossible with this setup. Given that we have official domains, we do not need these routings. Removing the routings allows koala to authenticate the user again.
Question: are we doing something wrong that we have to remove this reroutings, given that they have been there for ages?
=> fix: removed conflicting redirections
